/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamRouteImport } from './routes/stream'

const StreamRoute = StreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/stream': typeof StreamRoute
}
export interface FileRoutesByTo {
  '/stream': typeof StreamRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/stream': typeof StreamRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/stream'
  fileRoutesByTo: FileRoutesByTo
  to: '/stream'
  id: '__root__' | '/stream'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StreamRoute: typeof StreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stream': {
      id: '/stream'
      path: '/stream'
      fullPath: '/stream'
      preLoaderRoute: typeof StreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  StreamRoute: StreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
